### ISSUE TITLE
Numbers not getting displayed while showing the dataframe

### ISSUE THREAD

**Issue by jaaved** [bluenote10/PandasDataFrameGUI#13]
After python demo.py this is the result - it just displays strings, number values are blank:

![image](https://user-images.githubusercontent.com/3684795/29160525-3d584846-7dbb-11e7-9371-278540788f07.png)

**Comment by bluenote10** [comment]
I can't reproduce the problem. I tried several package versions under Linux and they all work. I assume this is a Windows specific problem maybe the same as #11. Do you happen to see the same error messages?

I have now pushed the tiny change I have mentioned in #11. Does this solve your problem?

**Comment by bluenote10** [comment]
This should be fixed after e260ac9.
