### ISSUE TITLE
Importing dfgui throws error

### ISSUE THREAD

**Issue by MushroomMaula** [bluenote10/PandasDataFrameGUI#15]
When I try to import dfgui i get this Error:
`File "C:\Python 3.6.2\lib\site-packages\dfgui\__init__.py", line 2, in <module>`
`from dfgui import show`
`ImportError: cannot import name 'show'`

**Comment by bluenote10** [comment]
You are using Python 3, and I would assume that this is a Python 3 issue. Note that unfortunately wxpython does not support Python 3, and thus, dfgui cannot support Python 3 either (https://github.com/bluenote10/PandasDataFrameGUI/issues/4).

**Comment by MushroomMaula** [comment]
Oh thank you didnt know that

**Comment by bluenote10** [comment]
@Nivya-V What do you mean by "from kivy python". Never heard of that before, seems to be a UI library that has nothing to do with dfgui? If you can import it in general this must be something related to your kivy setup (whatever that may be).
