### ISSUE TITLE
error import show

### ISSUE THREAD

**Issue by PierrenR** [bluenote10/PandasDataFrameGUI#16]
Hello,
Thank for your contribution. Sorry for my english, I'm French.

I have a problem :
it's ok for the download of dfgui and also wx
it's ok for the import : pandas/numpy  matplotlib wx

But when I try to import dfgui, I have this error : 
		 from dfgui import show
		ImportError: cannot import name 'show'

the error is in the file :      .\Anaconda3\Lib\site-packages\dfgui\__init__.py

Thank you very much
Pierre

**Comment by andreabotti** [comment]
Same issue here (installed through `pip` rather than conda). Any clue why this happens?

**Comment by bluenote10** [comment]
Is it possible that this is the same problem as #15 i.e. the lack of python 3 support?

**Comment by bluenote10** [comment]
Should be fixed by #18.
