### ISSUE TITLE
AttributeError: type object 'DataFrame' has no attribute 'from_list'

### ISSUE THREAD

**Issue by AsikuJoe** [bluenote10/PandasDataFrameGUI#30]
Hello, i seem not to figure out the issue here, when I change the attribute from from_list to  "from_dict" i get an inverted dataframe.

return pd.DataFrame.from_list

([
        ("Date", random_dates),
        ("UserID", choice(*user_ids)),
        ("ProductID", choice(*product_ids)),
        ("IntColumn", choice(1, 2, 3)),
        ("FloatColumn", choice(np.nan, 1.0, 2.0, 3.0)),
        ("StringColumn", choice("A", "B", "C")),
        ("Gaussian 1", np.random.normal(0, 1, size)),
        ("Gaussian 2", np.random.normal(0, 1, size)),
        ("Uniform", np.random.uniform(0, 1, size)),
        ("Binomial", np.random.binomial(20, 0.1, size)),
        ("Poisson", np.random.poisson(1.0, size)),
    ])

**Comment by bluenote10** [comment]
I don't understand what you mean. Yes, `pd.DataFrame` doesn't have a `from_list` method:

![image](https://user-images.githubusercontent.com/3620703/77820761-d6fd4b80-70e4-11ea-88b6-119743a6b4ec.png)

It is your responsibility to correctly construct a data frame.
