### ISSUE TITLE
support Python 3

### ISSUE THREAD

**Issue by zxweed** [bluenote10/PandasDataFrameGUI#4]
Will it support the 3.5 version of Python? wxPython seems to be not..

**Comment by bluenote10** [comment]
Good point. We probably have to wait until wxPython Phoenix will get 3.5 support.

**Comment by sho-87** [comment]
Does this work on python 3.x at all? Phoenix seems to be in alpha, and not much documentation on supported python versions

**Comment by bluenote10** [comment]
I didn't have time to look into Python 3.x yet. But since it all depends on wxPython, I probably can't do much about it. It's probably best to link this issue to some upstream issue.

**Comment by bluenote10** [comment]
Should work now after merging #18. Feel free to reopen if it doesn't work yet.
